name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/mq-python

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Build and publish to PyPI
        run: |
          uv sync
          uv build
          uv publish --trusted-publishing always
